[[libtree]]
arch = "aarch64"
git-tree-sha1 = "5da1b92dde379d84d1df464e05f5293476ceb91c"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "de0631346427cafd2a36468d1f33393196a47683b542bf9284a1731f02b5b56c"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.aarch64-linux-gnu.tar.gz"
[[libtree]]
arch = "aarch64"
git-tree-sha1 = "2afdbba09be601d45fe30ac7691423c4681dec2f"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "6031675abacb66284e854048ef5034664615c0c5be6575f190cf9be06970992a"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.aarch64-linux-musl.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de0c9bc0f3d0059fbc1b5c01ef42adee25425514"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "23a617805625f8c5b554365149d49cad62043761aa9834bb7db8168e51b62e65"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.armv6l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "231422c1dceba749fbb8ff035a286ab5ca930add"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "cbf8d0785f43c91251986ee860924760443c1765f2f7d0211c878f5a8b71f50f"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.armv6l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45bbf411ae5702aa49429fe2bba4a1a413f9f955"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "4a298d9eaf88281f58f7b014d9357c8915d1e2ae9cc82db6fb56843a8f9a5eb7"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.armv7l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94de711f8726768fde7dc9e7918b7fc9a6c5d58f"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "a4ec453d8d9965a106ce9ff868f73e25a4a69a7b27670ff8bc3d85e4b72eeb96"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.armv7l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "8ba4f9105d960c900634fceefde836dfe6bea5a5"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "589ad905ce503fe90c66a4690f0787c33102a9daa270633abf934681233cd0d8"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.i686-linux-gnu.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "f69f51524ab8f65513208d0d1cb40aaa841945b9"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "4697e57a2d31e5e8e15eccd356bdfbbe7a1479f22d397741e841f119779e2745"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.i686-linux-musl.tar.gz"
[[libtree]]
arch = "powerpc64le"
git-tree-sha1 = "b1a7b18cdafcb47e074b067c271e6e97bcebb85e"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "5bb94ec55525ea8fb9c9164e5e6b6a9e99a4c5b859b535f99e1d4737b7230cdf"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.powerpc64le-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "412e68c527e1b474864c1b7f3aaa5422f50c43a9"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "ed5682cef66166095decff64cf628a76ece1277a1d76eda5f5f45e214dafa194"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.x86_64-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "2bbdae05c392393f121dad152b0235263bcf9a98"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "557d38fc40a973b76ab094c30c3fe6f8bd9236d15347e5bb80207c3d911f4bc4"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.x86_64-linux-musl.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "94b3be08bf6e8b59d8d61628df8d9d2abf0b3762"
os = "freebsd"

    [[libtree.download]]
    sha256 = "78b6676925f45f9f653e9b3dc5daeff38222a4017e81ac440a895cced254d7d8"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.1.0+0/libtree.v3.1.0.x86_64-unknown-freebsd.tar.gz"
