[[libtree]]
arch = "aarch64"
git-tree-sha1 = "32682bfbf3f6ef098e37380c1982ce9a2b53f5f2"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "cce6c945c6a8c0037fd459d782a4228da7d87c4115f10a3b56b4446e55bb4704"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.aarch64-linux-gnu.tar.gz"
[[libtree]]
arch = "aarch64"
git-tree-sha1 = "8e1a768be685da627cd3abb6dda0bf6175a51e64"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "d0d8ff1d69e550a2df6d6d8ad94f0d41f23a4ededad504a622073d51d47f0874"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.aarch64-linux-musl.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53e23b3b3a5d7d6d2a84fcbc3f9340a021c03617"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "41657b4e4e7e2e5609827b20f23dafd7b58dd8e8bef5631c0985814673673922"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.armv6l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3edf19f5f7f0424e5333d9d5a9ce14e7ebc64334"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "b086d27756b2c5f869349913036262aabd1bdf50a587e417c1f9e6415c9834ab"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.armv6l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f69a82e0d52d32d96eadb6dcbabe8e2962758ba"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "87d63ffd8cc4ec00cd81607211f9cee8ba9ea944d36b7f29f35eebcbc8400ee7"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.armv7l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0ba048adaf91524dec1afb3ca03eb8a6f35e082"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "8ec337bc08262326293b1751e69688638e2b6d48d68ad1bf9e94afc33a6e6887"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.armv7l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "781d911d71b382c84e7f4347758462890aa219e0"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "e974e5f3f0eaea4a679041af74ca25323f71f1fac3dc0b5ac6e69a933a25537f"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.i686-linux-gnu.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "9a3794eca5e6ee3263f06e3cc6d41625eb227b2c"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "9c832cc9a5a6d641ae21aa17ed48a796138b6f2abada70a6b3d2564e842f5b9f"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.i686-linux-musl.tar.gz"
[[libtree]]
arch = "powerpc64le"
git-tree-sha1 = "c4c70243b624ec0743102c410a7f634bba7774e5"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "5e7bec2f8616116460e81a02d3711c4fbcf96500a13bdd5a7992ad49b8b8c89b"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.powerpc64le-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "35e1a1c83058282c18fc26d9d1e51f273bc1ded4"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "93f3a77416de0853c06363e8be45df30d5efb17dd9f97463fb009417d56a9765"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.x86_64-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "e5a1a278a97218f5bf06ff8b4f66987bea03d8b7"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "cfd1f2c2cb39130141b469f9d6f82408c572bebb26843e59beaf8e7a8bda15dd"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.x86_64-linux-musl.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "bfdc45885ae0a5097d0e6da2be5a5ab7e3584a78"
os = "freebsd"

    [[libtree.download]]
    sha256 = "27333eec332956de3223c22d249b39d8125232e0eebfe8c5d408561d53a066b7"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.3+0/libtree.v3.0.3.x86_64-unknown-freebsd.tar.gz"
