[[libtree]]
arch = "aarch64"
git-tree-sha1 = "ee6d902241dbfaaecde7d5aa86df8017efea23bb"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "774c58dbd55e08891e8060261feddc26fd4043241d0b556150a124c7ef12f483"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.aarch64-linux-gnu.tar.gz"
[[libtree]]
arch = "aarch64"
git-tree-sha1 = "acb6bc7af13f3b5f4b8243b46e36b70156285541"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "95289177916380277403f6af2a6ebb26eeb770947fabe117512121a779ea6794"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.aarch64-linux-musl.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4458824c54228cb91b388de974c44911b3a2d5b0"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "2a245fbbd304a69649a870b6045c1b83dc25ea80a626590a3641ecc72682e219"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f3c04ce4902cf69ece59435617aa80cddc829134"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "b415e768add6653746bca76d18cd0fa9f6b40b55125f6a56138ac7cf72fc9103"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.armv6l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8fd7b192dd4e983aba03dda6896ab8f0956eb48"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "e4226987e1c70d89b6e8cd203b9ad4599f985a3779e5fc6c730f981a0995e418"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libtree]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec9e7bf954657501ca549db832665ca695839727"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "d1dd386ed057f55d339996442247bb37e899e34ca7712c4fbaf080971bde3314"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.armv7l-linux-musleabihf.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "9574c37505863292b112a943ccbb3f88608d2c8c"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "6ed1c2f0f280180f5f7a0b8ded39db31018253f8b62cb64bff8778989edb5108"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.i686-linux-gnu.tar.gz"
[[libtree]]
arch = "i686"
git-tree-sha1 = "0b5d3b4f7bcd1244f2ef978f9e4cf4fc243128c8"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "62b2542ef7993eb9f07b6961ee7f08d2e03a1af7049c5c7fbfa713c178c328bd"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.i686-linux-musl.tar.gz"
[[libtree]]
arch = "powerpc64le"
git-tree-sha1 = "d61e6137edfa3c8ae0261487e2eba805577860ea"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "86d48201e7e2783041f9d0593e91f45f0f684738d51d75e4d25589b6fcf7c4d4"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.powerpc64le-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "64b9267a1bf36ab73934be621062c521e8a944fd"
libc = "glibc"
os = "linux"

    [[libtree.download]]
    sha256 = "3c6c5effc24b687006ceddf75b614683f529d42db7bec98ecb61ab7089d6e79b"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.x86_64-linux-gnu.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "f55deb1a1532d136495fc6e79c4980a1b3dd35b4"
libc = "musl"
os = "linux"

    [[libtree.download]]
    sha256 = "0e2feecd5e8ec4c701dbd4165d14820ad03b99093b5d67ca38097722677e0f31"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.x86_64-linux-musl.tar.gz"
[[libtree]]
arch = "x86_64"
git-tree-sha1 = "9f38d79e53d2b2f0009a4e6901c32441cc601d88"
os = "freebsd"

    [[libtree.download]]
    sha256 = "2dfabd4be4bb80afebb2ca61701555334f8a79bca75be960c0f650e10a8973db"
    url = "https://github.com/JuliaBinaryWrappers/libtree_jll.jl/releases/download/libtree-v3.0.1+0/libtree.v3.0.1.x86_64-unknown-freebsd.tar.gz"
